version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.5.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093
      KAFKA_LISTENER_INTERCEPTOR_CLASSES: io.confluent.monitoring.clients.interceptor.MonitoringInterceptor
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_INTERNAL: kafka:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      - kafkanet

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      KAFKA_CONSUMERGROUPS_ENABLED: 'true'
    ports:
      - "9000:9000"
    depends_on:
      - kafka
    networks:
      - kafkanet

networks:
  kafkanet:
    driver: bridge
